config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
 devise_scope :user do
    post '/sessions/user' => 'devise/sessions#create'
  end


  resources :sessions

  resources :rosters, only: [:create, :index, :destroy, :update, :show, :new]

  resources :rooms, only: [:create, :index] do
    post :leave
    post :join
  end

  root to: "welcome#index"
end

app/models/army.rb
class Army < ActiveRecord::Base
	has_many :rosters
	has_many :units
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :sessions

  validates_presence_of :name, :point_limit
  validates_uniqueness_of :name

  scope :empty, -> { joins("LEFT JOIN sessions ON sessions.room_id = rooms.id").where("sessions.room_id IS NULL") }

  before_create do
    self.communication_token = SecureRandom.hex(20)
  end

  def sessions_count
    sessions.count
  end
end

app/models/roster.rb
class Roster < ActiveRecord::Base
	has_many :troops
	has_many :units, :through => :troops
    belongs_to :army
    belongs_to :user
    
     accepts_nested_attributes_for :troops

    validates_presence_of :name, :points_limit, :user_id, :army_id
    validate :units_points_under_points_limit
    validate :slots_under_limits

    def units_points_under_points_limit
    	if troops.sum(:total_price) > points_limit
    		errors.add(:points_limit, "points overlimited")
    	end
    end

    def slots_under_limits
    	if units.where(slot:'Elite').count() > 1     ||
		   units.where(slot:'Tactical').count() > 1  ||
		   units.where(slot:'Artillery').count() > 2 ||
		   units.where(slot:'Mercanary').count() > 2
		   		errors.add(:troops, "slots overlimited")
		end
    end
	
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :room

  before_create do
    self.value = SecureRandom.hex(40)
  end

  scope :dead, ->{ where("alive_until < ?", Time.zone.now) }

  def mark_as_alive!
    update(alive_until: Time.now + 20.seconds)
  end
end

app/models/troop.rb
class Troop < ActiveRecord::Base
	belongs_to :unit
	belongs_to :roster

	before_save :default_values
	def default_values
	    self.total_price ||= unit.points * unit_size
	end

    validates_presence_of :unit_size

end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :troops
	has_many :rosters, :through => :troops
    belongs_to :army	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rosters

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception



  private

  def current_session
    @current_session ||= Session.find_by(value: params[:session_token])
  end

  def authenticated
    not_authenticated if params[:session_token].nil? || current_session.nil?
  end

  def not_authenticated
    head 401
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticated

  def index
    rooms = Room.all
    render json: rooms
  end

  def create
    room = Room.new(room_params)
    if room.valid?
      room.save
      current_session.update(room_id: room.id)
      render json: room
    else
      render json: { errors: room.errors.full_messages }, status: 422
    end
  end

  def leave
    current_session.update(room_id: nil)
    head :ok
  end

  def join
    room = Room.find_by(id: params[:room_id])
    if room.nil?
      head 404
    else
      current_session.update(room_id: room.id)
      render json: room
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, :point_limit)
  end
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
before_action :authenticate_user!, except: [:update]
  
  def index
    @rosters = Roster.where(user_id:current_user.id)
  end

def show
   @roster = Roster.includes(:troops).find(params[:id])
   @roster.user_id = current_user.id  
   @roster_json = RosterSerializer.new(@roster).to_hash.to_json
   @units = Unit.where(army_id: @roster.army_id)
end

def new
    @roster = Roster.new
   @roster.user_id = current_user.id  
    @army_options = Army.all.map{|u| [ u.name, u.id ] }    
end

  def create
    @roster = Roster.new(roster_params) 
   @roster.user_id = current_user.id  
    if @roster.valid?
      @roster.save
      redirect_to :action => 'show', :id => @roster.id
    else
      render json: { errors: @roster.errors.full_messages }, status: 422
    end
  end

  def update
    roster = Roster.find_by(id: params[:id])
    roster.troops.delete_all
    roster.update(roster_params)
    if roster.valid?
      roster.save
      render json: RosterSerializer.new(roster).to_hash
    else
      render json: { errors: roster.errors.full_messages }, status: 422
    end    
  end  

 def destroy
    @roster = Roster.find_by(id: params[:id])
    @roster.destroy
    redirect_to :action => 'index'
  end  

  private

  def roster_params
    params.require(:roster).permit(:id, :name, :army_id, :points_limit, troops_attributes: [:unit_id, :roster_id, :total_price, :unit_size])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session = Session.create
    session.mark_as_alive!
    render json: session
  end

  def update
    session = Session.find_by(value: params[:id])
    if session
      session.mark_as_alive!
      render json: session
    else
      head 404
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HeroesOfHex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>

app/views/rosters/index.html.erb
<h1>Listing Rosters</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Army</th>
    <th>Points limit</th>
    <th></th>
  </tr>
 
<% @rosters.each do |roster| %>
  <tr>
    <td><%= link_to roster.name, :action => 'show', :id => roster.id %></td>
    <td><%= roster.army.name %></td>    
    <td><%= roster.points_limit %></td>
    <td><%= link_to 'Destroy', roster_path(roster, :destroy =>true), :confirm =>'Are you sure?', :method => :delete %></td>    
  </tr>
<% end %>
</table>
 
<br>

<%= link_to 'New roster', :action => 'new' %>

app/views/rosters/new.html.erb
<h1>New roster</h1>


<%= form_for @roster, url: {action: "create"} do |f| %>
  <p>
    Name: <%= f.text_field 'name' %>
  </p>
  <p>
    Points limit: <%= f.number_field 'points_limit' %>
  </p>
  <p>
      Army:  <%= select(:roster, :army_id, @army_options) %>
  </p>
  <%= f.submit "Create" %>
<% end %>


<%= link_to 'Back', :action => nil %>

app/views/rosters/show.html.erb
<%= react_component('ArmyBuilder',
                    { roster: @roster_json,
                      units: @units}) %>
<%= link_to 'Back', :action => nil %>